# Define trigger
trigger:
  batch: true
  tags:
    include:
    - "*"
  branches:
      include:
        - debug
        - master

# Import necessary resources
resources:
  repositories:
    - repository: templates
      type: github
      name: isogeo/devops-templates
      endpoint: isogeo

stages:
# Create zip for saas deployment
 - stage: saas_integration
   condition: or(contains(variables['Build.SourceBranch'], 'refs/tags'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
   jobs : 
   - job : npm_build
     displayName : 'Npm build'
     steps : 
     - script: |
         npm install
       displayName: Install dependencies
     - task: ArchiveFiles@2
       inputs:
         rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
         includeRootFolder: false
       displayName: 'Archive files'
     - task: PublishBuildArtifacts@1
       displayName: 'Publish artifacts: drop'

# Build image
 - stage : image_build_update
   jobs :
   - template : /on-premises/docker_build_upload.yml@templates

# Upload image to blob
 - stage : upload_to_blob
   condition: and(succeeded(), or(contains(variables['Build.SourceBranch'], 'refs/tags'),eq(variables['Build.SourceBranch'], 'refs/heads/debug'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
   dependsOn : image_build_update
   variables : 
     zipName : $[ stageDependencies.image_build_update.image_build_and_upload.outputs['set_tag_variable.tag'] ]
   jobs:
   - template : /on-premises/upload_to_blob.yml@templates
     parameters : 
       zipName : $(NAME)-$(zipName).zip

# Update versions.json
 - stage: versions_update
   condition: contains(variables['Build.SourceBranch'], 'refs/tags')
   dependsOn : 
   - upload_to_blob
   jobs:
   - template : /on-premises/update_versions.yml@templates

# Tag installer
 - stage: installer_tag
   displayName : Tag Installer Version
   condition: contains(variables['Build.SourceBranch'], 'refs/tags')
   dependsOn: versions_update
   jobs : 
   - template : /on-premises/retrieve_github_pat.yml@templates
   - template : /on-premises/installer_tag.yml@templates
     parameters : 
      DependsOn : 'retrieve_pat'